app/controllers/AccountController.py
from app.authentication.login_required import customer_required
from app.dao import UserDao
from app import login
from app.dao.OrderDAO import find_all, find_add_by_user_id
from sendgrid.helpers.mail import Mail, Email, To, Content
from app.dao.UserDao import find_user_address, is_valid_email
from app.model.User import UserRole
from flask import render_template, request, redirect, url_for, session
from flask_login import login_user, logout_user, current_user
from flask import Blueprint
from app import db
from app.model.User import User
from app.model.Account import Account
import random
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from app import SENDGRID_API_KEY
import threading
import pdb

account_bp = Blueprint('account', __name__)

@account_bp.route('/purchase', methods=['GET'])
@customer_required
def purchase():
    payment_status = request.args.get('vnp_ResponseCode', default=None)

    if payment_status:
        return redirect(f'/account/purchase?payment={payment_status}')

    status = request.args.get('type', type=int)

    order = find_add_by_user_id(current_user.get_id(), status, 1, 5)

    order_to_dict = [order.to_detail_dict() for order in order]
    print(order_to_dict)
    is_success = request.args.get('payment', default=None)

    return render_template("profile/purchase.html", is_success=is_success, order=order_to_dict)


@account_bp.route('/admin-login', methods=['GET', 'POST'])
def admin_login():
    err_msg = ''
    if request.method == 'POST':
        identifier = request.form.get('username')
        password = request.form.get('password')

        user = UserDao.auth_user(identifier=identifier, password=password)
        if user:
            if user.user_role == UserRole.ADMIN:
                login_user(user=user)
                return redirect('/admin/')
            else:
                err_msg = "Vai trò không hợp lệ!"
        else:
            err_msg = "Tên đăng nhập hoặc mật khẩu không đúng!"

    return render_template('admin-login.html', err_msg=err_msg)


@account_bp.route("/admin-logout")
def admin_logout():
    logout_user()
    return redirect(url_for('account.admin_login'))


@account_bp.route("/admin-forgot", methods=['GET', 'POST'])
def admin_forgot():
    err_msg = ''
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        confirm = request.form.get('confirm')
        if not email or not password or not confirm:
            err_msg = 'Vui lòng điền đầy đủ thông tin!'
        else:
            email = email.strip()
            account = db.session.query(Account).join(User).filter(User.email == email).first()
            if account is None:
                err_msg = 'Email không tồn tại!'
            elif password != confirm:
                err_msg = 'Mật khẩu và xác nhận mật khẩu không trùng khớp!'
            else:
                UserDao.update_password(username=account.username, password=password)
                return redirect(url_for('account.admin_login'))

    return render_template("admin-forgotpass.html", err_msg=err_msg)


@account_bp.route('/employee-login', methods=['GET', 'POST'])
def employee_login():
    err_msg = ''
    if request.method == 'POST':
        identifier = request.form.get('username')
        password = request.form.get('password')

        user = UserDao.auth_user(identifier=identifier, password=password)
        if user:
            login_user(user=user)

            if user.user_role == UserRole.EMPLOYEE_SALE or user.user_role == UserRole.EMPLOYEE_MANAGER_WAREHOUSE or user.user_role == UserRole.EMPLOYEE_MANAGER:
                return redirect(url_for('employee.employee_profile'))
            else:
                err_msg = "Vai trò không hợp lệ!"
        else:
            err_msg = "Tên đăng nhập hoặc mật khẩu không đúng!"

    return render_template('employee-login.html', err_msg=err_msg)



@account_bp.route("/employee-logout")
def employee_logout():
    logout_user()
    return redirect(url_for('account.employee_login'))


@account_bp.route("/employee-verify-pass", methods=['GET', 'POST'])
def employee_verify_pass():
    err_msg = ''
    email = ''  # Khai báo biến email

    if request.method == 'POST':
        action = request.form.get('action')  # Kiểm tra hành động của form
        email = request.form.get('email')  # Email người dùng nhập vào
        input_code = request.form.get('verification_code')  # Mã xác nhận người dùng nhập

        if action == 'send_code':
            if not UserDao.check_exists_email(email=email):
                err_msg = 'Email không tồn tại!'
            else:
                if not is_valid_email(email):
                    err_msg = 'Email không hợp lệ!'
                    return render_template('employee-verify-pass.html', err_msg=err_msg, email=email)

                verification_code = random.randint(100000, 999999)  # Tạo mã xác nhận

                # Gửi mã xác nhận qua SendGrid trong một luồng riêng
                message = Mail(
                    from_email=Email('trinhgiaphuc24@gmail.com'),
                    to_emails=To(email),
                    subject='Mã xác nhận đăng ký',
                    plain_text_content=f'Mã xác nhận của bạn là: {verification_code}'
                )

                threading.Thread(target=send_email_async, args=(message,)).start()

                session['registration_data'] = {
                    'email': email,
                    'verification_code': verification_code
                }
                err_msg = 'Mã xác nhận đã được gửi đến email của bạn.'


        elif action == 'resend_code':
            if not UserDao.check_exists_email(email=email):
                err_msg = 'Email không tồn tại!'

            else:
                registration_data = session.get('registration_data', {})
                if not registration_data:
                    err_msg = 'Không tìm thấy dữ liệu email để gửi lại mã.'
                    return render_template('employee-verify-pass.html', err_msg=err_msg, email=email)

                email = registration_data.get('email')
                verification_code = random.randint(100000, 999999)  # Tạo mã xác nhận mới

                # Gửi lại mã xác nhận qua email trong một luồng riêng
                message = Mail(
                    from_email=Email('trinhgiaphuc24@gmail.com'),
                    to_emails=To(email),
                    subject='Mã xác nhận mới',
                    plain_text_content=f'Mã xác nhận mới của bạn là: {verification_code}'
                )

                threading.Thread(target=send_email_async, args=(message,)).start()

                registration_data['verification_code'] = verification_code
                session['registration_data'] = registration_data  # Cập nhật session

                err_msg = 'Mã xác nhận mới đã được gửi đến email của bạn.'

        elif action == 'confirm':
            if not UserDao.check_exists_email(email=email):
                err_msg = 'Email không tồn tại!'
            else:
                registration_data = session.get('registration_data', {})
                if not input_code:
                    err_msg = 'Vui lòng nhập mã xác nhận!'
                    return render_template('employee-verify-pass.html', err_msg=err_msg, email=email)

                if not registration_data:
                    err_msg = 'Không tìm thấy dữ liệu xác nhận. Vui lòng thử lại!'
                    return render_template('employee-verify-pass.html', err_msg=err_msg, email=email)

                if str(input_code) == str(registration_data.get('verification_code')):
                    return redirect(url_for('account.employee_forgot'))
                else:
                    err_msg = 'Mã xác nhận không đúng!'

    return render_template('employee-verify-pass.html', err_msg=err_msg, email=email)


@account_bp.route("/employee-forgot", methods=['GET', 'POST'])
def employee_forgot():
    err_msg = ''
    if request.method == 'POST':
        email = session.get('registration_data', {}).get('email', '')
        password = request.form.get('password')
        confirm = request.form.get('confirm')
        if not password or not confirm:
            err_msg = 'Vui lòng điền đầy đủ thông tin!'
        else:
            email = email.strip()
            account = db.session.query(Account).join(User).filter(User.email == email).first()
            if account is None:
                err_msg = 'Không tìm thấy tài khoản với email này!'
            elif password != confirm:
                err_msg = 'Mật khẩu và xác nhận mật khẩu không trùng khớp!'
            else:
                UserDao.update_password(username=account.username, password=password)
                return redirect(url_for('account.employee_login'))

    return render_template("employee-forgotpass.html", err_msg=err_msg)


@account_bp.route("/login", methods=['GET', 'POST'])
def login_process():
    err_msg = ''
    if request.method == 'POST':
        identifier = request.form.get('username')
        password = request.form.get('password')

        roles = [UserRole.CUSTOMER, UserRole.ADMIN, UserRole.EMPLOYEE_SALE, UserRole.EMPLOYEE_MANAGER,
                 UserRole.EMPLOYEE_MANAGER_WAREHOUSE]

        u = None
        for role in roles:
            u = UserDao.auth_user(identifier=identifier, password=password, role=role)
            if u:
                break
        if u:
            login_user(u)

            return redirect(url_for('index.index'))
        else:
            err_msg = "Tên đăng nhập hoặc mật khẩu không đúng!"

    return render_template("login.html", err_msg=err_msg)


@account_bp.route('/address')
@customer_required
def address():
    address_list = find_user_address(current_user.get_id())
    return render_template('profile/address.html', address_list=address_list)


@account_bp.route('/profile')
@customer_required
def profile():

app/controllers/CartController.py
import pdb

from flask import Blueprint, render_template, request, session, jsonify, redirect, url_for

from app.authentication.login_required import customer_required
from app.dao import AddressDAO
from app.dao.CartDao import find_by_user_id, find_by_cart_id, check_quantity
from flask_login import current_user, login_required

from app.dao.UserDao import find_user_address

from app.model.User import UserRole

cart_bp = Blueprint('cart', __name__)




@cart_bp.route('/')
@customer_required
def cart():
    cart = find_by_user_id(current_user.get_id())
    cart_result = check_quantity(cart.cart_items)
    print('test', cart_result)
    return render_template("cart.html", cart=cart_result)


@cart_bp.route('/checkout', methods=['GET', 'POST'])
def checkout():
    cart_ss = session.get('cartTick')

    if request.method.__eq__('POST'):
        data = request.json

        if cart_ss is None:
            cart_ss = []

        # Update the cart session with new data
        cart_ss = [{
            'bookId': int(item['bookId']),
            'img': item['img'],
            'quantity': int(item['quantity']),
            'price': float(item['price']),
            'title': item['title'],
        } for item in data]

        # Save the updated cart back into the session
        session['cartTick'] = cart_ss
        return jsonify({
            "status": "200",
            "message": "SUCCESS",
        })
    if cart_ss is None:
        return redirect(url_for('cart.cart'))

    cart_tick = session.get('cartTick')
    address_default = AddressDAO.find_by_user_id(1)
    address_user = find_user_address(current_user.get_id())
    total_price = 30000
    for item in cart_tick:
        total_price += item['price']

    return render_template('checkout-cart.html', cartTick=cart_tick, total_price=total_price,
                           address_default=address_default,
                           address_user=address_user)


@cart_bp.route('/get_all_sessions', methods=['GET'])
def get_all_sessions():
    # Retrieve all session data
    session_data = dict(session)  # Convert session to a regular dictionary
    return jsonify(session_data)


@cart_bp.route('/clear_session', methods=['POST', 'GET'])
def clear_session():
    session.clear()  # Remove all keys and their values from the session
    return jsonify({"message": "Session destroyed.", "status": 200})

app/controllers/HomeController.py
import pdb

import cloudinary
from flask import Blueprint
from flask import render_template, request
import json

from app.authentication.login_required import customer_no_user_required
from app.dao.BookDAO import find_by_gerne
from app.dao.BookGerneDAO import get_depth_gerne
from app.dao.SearchDAO import search_book
from app.utils.admin import profile
from datetime import datetime
import hashlib
from flask_login import current_user
from app.model.User import User
from flask import jsonify
from app import db

index_bp = Blueprint('index', __name__)


@index_bp.route("/")
@customer_no_user_required
def index():
    book_gerne = get_depth_gerne(1)

    sub_gerne = book_gerne['sub_gerne'][0:4]

    advertised_category_image = [
        'https://cdn0.fahasa.com/media/wysiwyg/Thang-11-2024/catehomepage_vanhoc.jpg',
        'https://cdn0.fahasa.com/media/wysiwyg/Thang-11-2024/catehomepage_manga.jpg',
        'https://cdn0.fahasa.com/media/wysiwyg/Thang-11-2024/catehomepage_ngoaingu.jpg',
        'https://cdn0.fahasa.com/media/wysiwyg/Thang-11-2024/catehomepage_kynang.jpg'
    ]
    idx = 0
    for category in sub_gerne:
        book = search_book(gerne_id=category['id'], limit=3)
        category['advertised_image'] = advertised_category_image[idx]
        category['books'] = [book.images[0].image_url if len(book.images) else None for book in book['books']]
        idx += 1

    new_release = search_book(order='created_at', direction='desc', limit=8)['books']
    bestselling_books = search_book(order='created_at', direction='desc', limit=5)['books']

    return render_template("home.html",
                           bestselling_books=bestselling_books,
                           new_release=new_release,
                           category_section=sub_gerne)


@index_bp.route('/update-profile', methods=['POST'])
def update_profile():
    try:
        data = request.form
        user = User.query.filter_by(user_id=current_user.user_id).first()

        if not user:
            return jsonify({"success": False, "message": "User not found"}), 404

        account = user.account
        if not account:
            return jsonify({"success": False, "message": "Account not found"}), 404

        user.first_name = data.get('first_name', user.first_name)
        user.last_name = data.get('last_name', user.last_name)
        user.email = data.get('email', user.email)
        user.phone_number = data.get('phone_number', user.phone_number)
        user.sex = False if data.get('sex') == '0' else True
        user.date_of_birth = data.get('date_of_birth', user.date_of_birth)
        # user.avt_url = data.get('avt_url', user.avt_url)
        if request.files:
            image = request.files.get('avt_url')

            res = cloudinary.uploader.upload(image)
            image_url = res['secure_url']

            user.avt_url = image_url

        current_password = data.get('password')
        new_password = data.get('newpassword')
        confirm_password = data.get('confirm')

        if current_password and new_password and confirm_password:
            # Hash mật khẩu hiện tại và so sánh với mật khẩu trong Account
            current_password_hashed = hashlib.md5(current_password.encode('utf-8')).hexdigest()
            if current_password_hashed != account.password:
                return jsonify({"success": False, "message": "Mật khẩu hiện tại không chính xác"}), 400

            # Kiểm tra mật khẩu mới và xác nhận mật khẩu
            if new_password != confirm_password:
                return jsonify({"success": False, "message": "Mật khẩu không trùng khớp"}), 400

            # Cập nhật mật khẩu mới
            account.password = hashlib.md5(new_password.strip().encode('utf-8')).hexdigest()

        db.session.commit()

        return jsonify({"success": True, "updated": data}), 200
    except Exception as e:
        db.session.rollback()
        return jsonify({"success": False, "message": str(e)}), 500

app/templates/admin-verify-pass.html
<!DOCTYPE html>
<html>

<head>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.css"
          crossorigin="anonymous"/>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="keywords" content="html, html5, web, css, js">
    <meta name="description" content="GPHUCDEPZAI">
    <meta http-equiv="refresh" content="1800">
    <link href="https://cdn0.fahasa.com/media/favicon/default/favicon4.ico" rel="shortcut icon">
    <title>Đăng kí</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <script src="wow.min.js"></script>
</head>

<body>
<div class="main-wrapper login-body">
    <div>
        <div class="row">
            <div class="login-wrap">
                <div class="login-sec">
                    <div>
                        <img src="https://res.cloudinary.com/duk7gxwvc/image/upload/v1732125348/385-3855617_click-here-for-flyer-kids-reading-reading-week-removebg-preview_asryy5.png"
                             alt="Login Image">
                    </div>
                </div>
            </div>
            <div class="login-wrap-bg">
                <div class="login-wrapper">
                    <div class="loginbox">
                        <div class="login-right">
                            <div class="login-right-wrap">
                                <div class="account-logo row">
                                    <a href="javascript:;">
                                        <img class="img1"
                                             src="https://cdn0.fahasa.com/skin/frontend/ma_vanese/fahasa/images/fahasa-logo.png"
                                             alt="">
                                    </a>
                                </div>
                                <h2 style="color: #5a5a5a;">Xác nhận email</h2>
                                <form class="row" method="post" action="{{ url_for('account.admin_verify_pass') }}" id="verificationForm">
                                    <!-- Email -->
                                    <div class="form-group-2 appoinment-body-1" style="width: 102%;">
                                        <div class="form-group appoinment-body-1">
                                            <label for="email">
                                                <font>Email</font>
                                                <span style="color: red;">*</span>
                                            </label>
                                        </div>
                                        <div>
                                            <input class="form-control-all form-control-ten-sdt-checkpass" type="email"
                                                   id="email" name="email" value="{{ email }}" required>
                                        </div>
                                    </div>

                                    <!-- Verification Code -->
                                    <div class="form-group-1 appoinment-body-1">
                                        <div class="form-group appoinment-body-1">
                                            <label for="verify">
                                                <font>Mã xác nhận</font>
                                                <span style="color: red;">*</span>
                                            </label>
                                        </div>
                                        <div>
                                            <input class="form-control-all form-control-ten-sdt-checkpass" type="text"
                                                   id="verify" name="verification_code">
                                        </div>
                                    </div>

                                    <!-- Buttons -->
                                    <div class="form-group-1" style="width:23%">
                                        <div class="form-group appoinment-body-1">
                                            <label>
                                                <font></font>
                                            </label>
                                        </div>
                                        <div class="box">
                                            <button class="btn-primary" type="submit" name="action" value="send_code" id="sendCodeBtn">
                                                Gửi mã
                                            </button>
                                        </div>
                                    </div>
                                    <div class="form-group-2" style="width:23%">
                                        <div class="form-group appoinment-body-1">
                                            <label>
                                                <font></font>
                                            </label>
                                        </div>
                                        <div class="box">
                                            <button class="btn-primary" type="submit" name="action" value="resend_code" id="resendCodeBtn">
                                                Gửi lại
                                            </button>
                                        </div>
                                    </div>
                                    <div class="container-checkpass">
                                        {% if err_msg %}
                                        <div class="checkpass" style="margin-bottom: 15px">
                                            <div class="remember-me">
                                                <label class="custom_check">
                                                    <font style="color: red; font-weight: 600;">{{err_msg}}</font>
                                                    <span class="checkmark"></span>
                                                </label>
                                            </div>
                                        </div>
                                        {% endif %}
                                    </div>
                                    <div class="form-group login-btn" style="margin-top:15px;">
                                        <div class="box">
                                            <button class="btn-primary" type="submit" name="action" value="confirm">Xác
                                                nhận
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

app/templates/employee-verify-pass.html
<!DOCTYPE html>
<html>

<head>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.css"
          crossorigin="anonymous"/>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="keywords" content="html, html5, web, css, js">
    <meta name="description" content="GPHUCDEPZAI">
    <meta http-equiv="refresh" content="1800">
    <link href="https://cdn0.fahasa.com/media/favicon/default/favicon4.ico" rel="shortcut icon">
    <title>Đăng kí</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <script src="wow.min.js"></script>
</head>

<body>
<div class="main-wrapper login-body">
    <div>
        <div class="row">
            <div class="login-wrap">
                <div class="login-sec">
                    <div>
                        <img src="https://res.cloudinary.com/duk7gxwvc/image/upload/v1732125348/385-3855617_click-here-for-flyer-kids-reading-reading-week-removebg-preview_asryy5.png"
                             alt="Login Image">
                    </div>
                </div>
            </div>
            <div class="login-wrap-bg">
                <div class="login-wrapper">
                    <div class="loginbox">
                        <div class="login-right">
                            <div class="login-right-wrap">
                                <div class="account-logo row">
                                    <a href="javascript:;">
                                        <img class="img1"
                                             src="https://cdn0.fahasa.com/skin/frontend/ma_vanese/fahasa/images/fahasa-logo.png"
                                             alt="">
                                    </a>
                                </div>
                                <h2 style="color: #5a5a5a;">Xác nhận email</h2>
                                <form class="row" method="post" action="{{ url_for('account.employee_verify_pass') }}" id="verificationForm">
                                    <!-- Email -->
                                    <div class="form-group-2 appoinment-body-1" style="width: 102%;">
                                        <div class="form-group appoinment-body-1">
                                            <label for="email">
                                                <font>Email</font>
                                                <span style="color: red;">*</span>
                                            </label>
                                        </div>
                                        <div>
                                            <input class="form-control-all form-control-ten-sdt-checkpass" type="email"
                                                   id="email" name="email" value="{{ email }}" required>
                                        </div>
                                    </div>

                                    <!-- Verification Code -->
                                    <div class="form-group-1 appoinment-body-1">
                                        <div class="form-group appoinment-body-1">
                                            <label for="verify">
                                                <font>Mã xác nhận</font>
                                                <span style="color: red;">*</span>
                                            </label>
                                        </div>
                                        <div>
                                            <input class="form-control-all form-control-ten-sdt-checkpass" type="text"
                                                   id="verify" name="verification_code">
                                        </div>
                                    </div>

                                    <!-- Buttons -->
                                    <div class="form-group-1" style="width:23%">
                                        <div class="form-group appoinment-body-1">
                                            <label>
                                                <font></font>
                                            </label>
                                        </div>
                                        <div class="box">
                                            <button class="btn-primary" type="submit" name="action" value="send_code" id="sendCodeBtn">
                                                Gửi mã
                                            </button>
                                        </div>
                                    </div>
                                    <div class="form-group-2" style="width:23%">
                                        <div class="form-group appoinment-body-1">
                                            <label>
                                                <font></font>
                                            </label>
                                        </div>
                                        <div class="box">
                                            <button class="btn-primary" type="submit" name="action" value="resend_code" id="resendCodeBtn">
                                                Gửi lại
                                            </button>
                                        </div>
                                    </div>
                                    <div class="container-checkpass">
                                        {% if err_msg %}
                                        <div class="checkpass" style="margin-bottom: 15px">
                                            <div class="remember-me">
                                                <label class="custom_check">
                                                    <font style="color: red; font-weight: 600;">{{err_msg}}</font>
                                                    <span class="checkmark"></span>
                                                </label>
                                            </div>
                                        </div>
                                        {% endif %}
                                    </div>
                                    <div class="form-group login-btn" style="margin-top:15px;">
                                        <div class="box">
                                            <button class="btn-primary" type="submit" name="action" value="confirm">Xác
                                                nhận
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

app/templates/error-page.html
{% extends 'layout/base.html' %}

{% block content %}
    <div class="my-bg-color pt-3 pb-3">
        <div class="container">
            <div class="item-bg-color h-50vh d-flex flex-column justify-content-center align-items-center">
                <i style="font-size: 50px" class="text-secondary fa-solid fa-circle-info"></i>

                <h1 class="text-primary p-4 text-center">
                    Đã có lỗi lỗi xảy ra. Vui lòng liên hệ Admin để được giúp đỡ
                </h1>
                <a class="text-primary text-large" href="/">Quay về trang chủ</a>
            </div>
        </div>
    </div>
{% endblock %}